// <auto-generated />
using System;
using DataBase.MyDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataBase.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DataBase.DbEntity.GameAccount", b =>
                {
                    b.Property<Guid>("GameAccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameAccountId");

                    b.ToTable("GameAccounts");
                });

            modelBuilder.Entity("DataBase.DbEntity.GameCharacter", b =>
                {
                    b.Property<Guid>("GameCharacterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DiscriptionGameChar")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameCharacterName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameCharacterId");

                    b.ToTable("GameCharacters");
                });

            modelBuilder.Entity("DataBase.DbEntity.GameClass", b =>
                {
                    b.Property<Guid>("GameClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DescriptionGameClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GameClassName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameClassId");

                    b.ToTable("GameClasss");
                });

            modelBuilder.Entity("DataBase.DbEntity.Group", b =>
                {
                    b.Property<Guid>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GroupName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupId");

                    b.ToTable("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
